---
title: "Map"
subtitle: ""
description: ""
author: "Holly Gustavsen"
date: "2023-11-08"
image: ""
image-alt: ""
categories: []
date-modified: "2023-12-06"
draft: TRUE
---
```{r} 
suppressPackageStartupMessages(library(tidyverse)) 
suppressPackageStartupMessages(library(ggplot2)) 
suppressPackageStartupMessages(library(stringr)) 

crash_data <- read_csv(here::here("dataset-ignore", "Crash_Reporting_-_Incidents_Data.csv"),          show_col_types = FALSE) 

crash_data_clean <- crash_data |>      
  select(Latitude,          
         Longitude,          
         "Driver Substance Abuse", 	          
         "Collision Type") |>   
  rename(driver_substance_abuse = "Driver Substance Abuse", type = "Collision Type") 

traffic_data_2 <- read_csv(here::here("dataset-ignore", "Traffic_Violations_20231103.csv"),          show_col_types = FALSE) 

traffic_data_2_clean <- traffic_data_2 |>      
  select(Alcohol,          
         "Violation Type",          
         Latitude,          
         Longitude) |>   
  rename(driver_substance_abuse = "Alcohol", type = "Violation Type") 
```

```{r} 
combined <- union(crash_data_clean, traffic_data_2_clean) |>   
  filter(between(Latitude, 38.8, 39.6), between(Longitude, -78, -76.5)) 
``` 

```{r} 
library(tidycensus) 
library(sf) 
``` 

```{r}
# census_api_key("d60e1c9aa5c6a445f991501def579b743fc1a5d8", install = TRUE) 
``` 

```{r} 
v2020 <- load_variables(2020, "pl", cache = TRUE)

vars10 <- c("P1_003N", "P1_004N", "P1_005N", "P1_006N", "P1_007N") 

md <- get_decennial(geography = "block group", variables = vars10, year = 2020,           
                    summary_var = "P1_001N", state = "MD", county = c("Montgomery county"), 
                    geometry = TRUE) %>%   
  mutate(pct = 100 * (value / summary_value)) 

combined_geo <- combined |>   
  st_as_sf(coords = c("Longitude", "Latitude")) %>%   
  st_set_crs(4269) 
``` 

```{r} 
ggplot() + geom_sf(data = md, aes(fill = pct)) + facet_wrap(~variable) 
```

```{r} 
ggplot() + geom_sf(data = md, aes(fill = pct)) + 
  geom_sf(data = combined_geo, aes(color = type, alpha = 0.05, size = 0.01)) + 
  facet_wrap(~variable) 
```
simplified version: 

```{r}
crash_only <- crash_data_clean |>
  mutate(type = "collision")

traffic_only <- traffic_data_2_clean |>
  mutate(type = "traffic violation")

simplified <- union(crash_only, traffic_only) |>   
  filter(between(Latitude, 38.8, 39.6), between(Longitude, -78, -76.5)) 

simplified_geo <- simplified |>   
  st_as_sf(coords = c("Longitude", "Latitude")) %>%   
  st_set_crs(4269) 
```

```{r} 
ggplot() + geom_sf(data = md, aes(fill = pct)) + 
  geom_sf(data = simplified_geo, aes(color = type), alpha = 0.1, size = 0.1) + 
  facet_wrap(~type) 
``` 

```{r}
simplified |>
  count(type)
```


