---
title: "Blog post 6"
subtitle: ""
description: ""
author: "Team 9"
date: "2023-12-01"
image: ""
image-alt: ""
categories: []
date-modified: "2023-12-01"
draft: FALSE
---

We tried a number of different exploratory data analysis, and here is one example. We believe GLM (“general” linear model) could explain our dataset better than other tools. This is the code we used:

```{r}
traffic_data_clean$Arrest_Type_Numeric <- ifelse(grepl("Marked", traffic_data_clean$`Arrest Type`), 1, 0)
model <- glm(Arrest_Type_Numeric ~ Race + Alcohol + Gender, data = traffic_data_clean, family = "binomial")
summary(model)
```

We first changed the categorical variable into a numeric variable of 0 and 1 to run the test. If the word “Marked” is contained, the value of 1 is assigned. If not, 0 is assigned. Based on Race, Alcohol, and Gender, we tried to predict the probability of Arrest Type. The intercept is 2.725248; this is the log-odds of the Arrest Type when all other predictor variables are zero. 
We are still trying out different EDA, with GLM being the priority. We are still unsatisfied with produced results, but we believe we could reach a conclusion that everyone can agree.
We plan to polish our visualizations and tables after finalizing our model to best show the data in terms of our method of statistical modeling. This will include highlighting information that informed the variables we made the decision to include. For example, in our scatterplot from our exploratory data analysis we will highlight the variables race, alcohol, and gender which seemed to have a potential relationship with arrest_type_numeric to show that this contributed to these variables being chosen for our statistical model. We also plan to add titles to our visualizations and tables to more clearly show what is being modeled in that particular plot. Additionally, we will polish up our data visualizations by adding captions and annotations to write a short summary of what our takeaways from that visualization were. For example, in the scatterplot mentioned before we will add a caption or annotation saying that only race, alcohol, and gender appear to potentially have a relationship with arrest_type_numeric. We also plan to improve our figures using the options for displaying tables from https://gallery.htmlwidgets.org/, particularly the scatterD3 option to include both colors and comments more clearly for specific points in our plots. We are also planning to use pairsD3 to be able to show various relationships between variables that we explored to choose our model. 


